require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'StayPut' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
 
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  
  pod 'rn-fetch-blob',
      :path => '../node_modules/rn-fetch-blob'
      
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'react-native-payments', :path => '../node_modules/react-native-payments'

  pod '@mauron85_react-native-background-geolocation', :path => '../node_modules/@mauron85/react-native-background-geolocation'


  pod 'react-native-branch', :path => '../node_modules/react-native-branch'

  target 'StayPutTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
